layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
   facebook: jamilusalisofficial
  # hackerrank: your_username
   instagram: jamilusalis
  # keybase: your_username
   linkedin: jamilusalis
  # mastodon: your_username
   medium: jamilusalis
  # stackoverflow: your_user_id
   telegram: jamilusalis
   twitter: majorstation
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
   youtube: JamiluSalis

topics:
  - name: Azure
    web_url: https://github.com/topics/azure
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png
    
  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png
    
  - name: ASP.NET
    web_url: https://github.com/topics/aspnet
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/aspnet/aspnet.png
    
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: JavaScript
    web_url: hhttps://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png
    
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
    

theme: jekyll-theme-leap-day